-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS F
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
AND PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT AS F2
    WHERE F.CATEGORY = F2.CATEGORY
)
ORDER BY MAX_PRICE DESC;
